plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.11'
}

dependencies {
    implementation project(':consumer-balancer-spring-boot-starter')
    implementation project(':consumer-balancer-core')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
}
