plugins {
    id 'java-library'
    id "com.vanniktech.maven.publish" version "0.36.0"
}

version = project.findProperty("version")
group = project.findProperty("group")

dependencies {
    api 'org.apache.kafka:kafka-clients'
    implementation 'org.slf4j:slf4j-api'
    implementation 'tools.jackson.core:jackson-databind'
    testRuntimeOnly 'ch.qos.logback:logback-classic'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

mavenPublishing {
  coordinates(group, "consumer-balancer-core", version)

  pom {
    name = "Consumer Balancer Core"
    description = "A library for balancing Kafka partitions based on load."
    inceptionYear = "2026"
    url = "https://github.com/ruskaof/consumer-balancer"
    licenses {
      license {
        name = "The Apache License, Version 2.0"
        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
        distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
      }
    }
    developers {
      developer {
        id = "ruskaof"
        name = "Dmitrii Rusinov"
        url = "https://github.com/ruskaof"
      }
    }
    scm {
      url = "https://github.com/ruskaof/consumer-balancer"
    }
  }
}

